<?php

namespace Dasundev\PayHere\Enums;

enum MessageType: string
{
    case AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
    case AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';
    case RECURRING_INSTALLMENT_SUCCESS = 'RECURRING_INSTALLMENT_SUCCESS';
    case RECURRING_INSTALLMENT_FAILED = 'RECURRING_INSTALLMENT_FAILED';
    case RECURRING_COMPLETE = 'RECURRING_COMPLETE';
    case RECURRING_STOPPED = 'RECURRING_STOPPED';
}
